### ISSUE TITLE
Does the theme update code only run if the theme is active?

### ISSUE THREAD

**Issue by deanhamilton11** [froger-me/wp-package-updater#3]
I've got a parent theme hooked up to a wordpress installation running wp-plugin-update-server, the new versions are correctly reflected in wp-plugin-update-server, but our site with the parent theme installed doesn't have any updates available.

Is this because we are using a parent theme, and since it isn't actually active, the code to update the theme never runs?

Thanks.

**Comment by froger-me** [comment]
Hello @deanhamilton11 !

It seems you've hit one of the several limits of the updater library.

Indeed, it necessitates a plugin/theme to be active to be fired - in the case of parent themes, I am not quite sure how or even whether the code in `functions.php` is executed when checking for updates.

However, WP Package Updater is designed to be lean but fairly flexible: feel free to extend it and experiment with it - at the moment I am focusing on maintenance for WPPUS, and do not have a timeline yet as to when I will add new features.

**Comment by deanhamilton11** [comment]
Thanks, that makes sense. You've saved me a whole lot of troubleshooting effort!
