### ISSUE TITLE
Parse error: syntax error, unexpected '='

### ISSUE THREAD

**Issue by onliniak** [froger-me/wp-package-updater#5]
WP 5.0.3
PHP 7.3.1

require_once plugin_dir_path( __FILE__ ) . 'lib/wp-package-updater/class-wp-package-updater.php';

$ocean-cream = new WP_Package_Updater(
  'https://github.com/onliniak/',
  wp_normalize_path( __FILE__ ),
  wp_normalize_path( plugin_dir_path( __FILE__ ) ),
  true
);

**Comment by froger-me** [comment]
Hi @onliniak 
You have a syntax error in your own code: variables in PHP cannot include a `-`, like in the variable `$ocean-cream`. It should be `$ocean_cream` (WordPress syntax) or `$oceanCream` (camelCase).

Please note the target audience of this library is developers working with [WP Plugin Update Server](https://wordpress.org/plugins/wp-plugin-update-server/), not users working directly with Github (therefor the first parameter passed to the `WP_Package_Updater` is wrong).

Cheers!
